<?php

namespace Tests\Feature;

use App\Models\FoodCategory;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class FoodCategoryTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $role = Role::factory()->create(['name' => 'admin', 'display_name' => 'Admin', 'description' => 'Admin']);
        $this->user = User::factory()->create();
        $this->user->roles()->attach($role);

        Sanctum::actingAs(
            $this->user,
            ['*']
        );

        $this->foodCategory = FoodCategory::factory()->create();
    }

    public function test_admin_fetch_all_food_categories()
    {
        $response = $this->getJson(route('food-categories.index'))
            ->assertOk();

        $this->assertEquals(1, $this->count($response->json()));
        $this->assertEquals($this->foodCategory->category_name, $response['category_name']);
    }
}
