insert  into `food_categories`(`id`,`category_name`) values
(1,'Serealia'),
(2,'Serealia Olahan'),
(3,'Umbi Berpati'),
(4,'Umbi Berpati Olahan'),
(5,'Kacang, Biji'),
(6,'Kacang, Biji Olahan'),
(7,'Sayuran'),
(8,'Sayuran Olahan'),
(9,'Buah'),
(10,'Buah Olahan'),
(11,'Daging, Unggas'),
(12,'Daging, Unggas Olahan'),
(13,'Ikan, Kerang, Udang'),
(14,'Ikan, Kerang, Udang Olahan'),
(15,'Telur'),
(16,'Telur Olahan'),
(17,'Susu'),
(18,'Susu Olahan'),
(19,'Lemak dan Minyak'),
(20,'Lemak dan Minyak Olahan'),
(21,'Gula, Sirup'),
(22,'Bumbu'),
(23,'Bumbu Olahan'),
(24,'Minuman');
