<?php

namespace Tests\Unit;

use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class RoleTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->roleUser = Role::factory()->create(['name' => 'user', 'display_name' => 'User', 'description' => 'User']);

        $this->userUser = User::factory()->create();
        $this->userUser->roles()->attach($this->roleUser);
    }

    public function test_role_belongs_to_many_user()
    {
        $this->assertInstanceOf(Collection::class,  $this->roleUser->users);
        $this->assertInstanceOf(User::class,  $this->roleUser->users->first());
    }
}
